#!/bin/bash
# remove zip and .pdf files from the project directory then regenerate them
#
MYFULLNAME=$0
MYPROGNAME=`/usr/bin/basename ${MYFULLNAME}` 
MYPROGDIR=`/usr/bin/dirname ${MYFULLNAME}`
pushd ${MYPROGDIR} >/dev/null
MYPATH=`/bin/pwd`
popd >/dev/null
cd ${MYPATH}
ZIPFILE="compiled_docs_mathsansmystere_`/bin/date -u --rfc-3339=date`.zip"
echo generating/regenerating ${ZIPFILE} in ${MYPATH}
MYNAMES=`/usr/bin/find . -maxdepth 1 -name "*.tex" | /usr/bin/xargs -L 1 /usr/bin/basename -s .tex`
echo /bin/rm --force ${ZIPFILE}
for aname in ${MYNAMES}
do
   echo /bin/rm --force ${aname}.pdf
   /bin/rm --force ${aname}.pdf
   echo /usr/bin/pdflatex ${aname}.tex
   /usr/bin/pdflatex ${aname}.tex
   echo /usr/bin/7z a ${ZIPFILE} ${aname}.pdf
   /usr/bin/7z a ${ZIPFILE} ${aname}.pdf
done
#/usr/bin/pdflatex
#/bin/rm --force *.pdf
# /bin/rm --force ${ZIPFILE}
#
#7z a compiled_docs_mathsansmystere_`/bin/date -u --rfc-3339=date`.zip *.pdf
