#!/bin/bash
# inspect tex subdirectory for each latex document for comment lines
#
MYFULLNAME=$0
MYPROGNAME=`/usr/bin/basename ${MYFULLNAME}` 
MYPROGDIR=`/usr/bin/dirname ${MYFULLNAME}`
pushd ${MYPROGDIR} >/dev/null
MYPATH=`/bin/pwd`
popd >/dev/null
cd ${MYPATH}
MYNAMES=`/usr/bin/find . -maxdepth 1 -name "*.tex" | /usr/bin/xargs -L 1 /usr/bin/basename -s .tex`
for aname in ${MYNAMES}
do
   echo ${aname} `/bin/ls tex/${aname}/ | wc -l` questions
   find tex/${aname}/ -maxdepth 1 -type f -exec head -1 {} \; | sort
done
